# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: CI Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci-integration:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install requirements lib
      run: python -m pip install -r requirements.txt
    
    - name: Flake8 check
      run: flake8
    
    - name: Run python test
      run: python test_model.py
      working-directory: starter/starter/ml/
